### ISSUE TITLE
Miri test failure with --no-default-features

### ISSUE THREAD

**Issue by taiki-e** [smol-rs/event-listener#84]
https://github.com/smol-rs/event-listener/actions/runs/6367362187/job/17285871726

```
failures:

---- sys::tests::listener_slab_notify_prop stdout ----
thread 'sys::tests::listener_slab_notify_prop' panicked at src/no_std.rs:1270:9:
assertion `left == right` failed
  left: Listener { state: Task(_), prev: Cell { value: None }, next: Cell { value: Some(3) } }
 right: Listener { state: Task(_), prev: Cell { value: None }, next: Cell { value: Some(3) } }
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:72:14
   2: core::panicking::assert_failed_inner
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:[31](https://github.com/smol-rs/event-listener/actions/runs/6367362187/job/17285871726#step:6:32)5:17
   3: core::panicking::assert_failed::<sys::Entry<()>, sys::Entry<()>>
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:270:5
   4: sys::tests::listener_slab_notify_prop
             at src/no_std.rs:1270:9
   5: sys::tests::listener_slab_notify_prop::{closure#0}
             at src/no_std.rs:1119:[36](https://github.com/smol-rs/event-listener/actions/runs/6367362187/job/17285871726#step:6:37)
   6: <{closure@src/no_std.rs:1119:5: 1361:6} as std::ops::FnOnce<()>>::call_once - shim
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
   7: <fn() -> std::result::Result<(), std::string::String> as std::ops::FnOnce<()>>::call_once - shim(fn() -> std::result::Result<(), std::string::String>)
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:2[50](https://github.com/smol-rs/event-listener/actions/runs/6367362187/job/17285871726#step:6:51):5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    sys::tests::listener_slab_notify_prop
```

Failed assertion is:

https://github.com/smol-rs/event-listener/blob/d2ed2cdbf272c6aa164f758e6947892242299d3b/src/no_std.rs#L1270-L1277

This reminded me of https://github.com/rust-lang/rust/issues/66281, but I have not looked if it is related.

cc @notgull

**Comment by notgull** [comment]
Comparing the waker might not work correctly in all cases. Will look into this.
